### ISSUE TITLE
Ajax call is not working,

### ISSUE THREAD

**Issue by virajsonagra** [cheezytony/vue-datatable#2]
Hi,
Ajax call is not working properly data is not displaying after the response.
How can we set the pagination and iteam per page it always stay 100. What if i wants to set it to 10

**Comment by cheezytony** [comment]
Thanks for your feedback and I'm incredibly sorry for the late response.
I'm currently working on an update that would handle this where you can set your preferred limit as a prop as well as other features.

**Comment by cheezytony** [comment]
And as for the ajax data your response would have to come with a data property containing the array of data

**Comment by cheezytony** [comment]
`
{
    data: [
        { ... },
        { ... },
        { ... }
    ],
    success: true
}
`

**Comment by virajsonagra** [comment]
Thank you so much for the response. This plugin is going to Rock if a few things start working like localization and the pagination issue.

> `{ data: [ { ... }, { ... }, { ... } ], success: true }`

above response is mandatory.

- what if i send the data only in response? 
Like `[{...},{...},{...},{...}]`

and since i have hundreds of record if the pagination works automatically?  how you calculate total pages and records with ajax? Because initially i want only 10 records based on the 'recordperpage' selection and when i click on next it will load next 10 records and so on...

**Comment by cheezytony** [comment]
That makes sense, i think i'll make it possible to accept multiple response structures.
