### ISSUE TITLE
Can't use onclick event

### ISSUE THREAD

**Issue by arkgnan** [cheezytony/vue-datatable#5]
I try use this onclick event. but I get error
`<datatable :data="data" :columns="columns" :onclick="click"></datatable>`  

```
methods: {
    click(row, cell, name, index) {

    }
}
```

![Screenshot_2](https://user-images.githubusercontent.com/17277219/94261259-c296f000-ff5b-11ea-9289-51a0de4a11ae.png)  

@cheezytony  could you help me?

**Comment by cheezytony** [comment]
Hey @arkgnan thanks for reaching out...
So the problem here is that the property name is “onClick” and you specified “onclick”. It’s actually in camel case and not all lowercase

**Comment by arkgnan** [comment]
> Hey @arkgnan thanks for reaching out...
> So the problem here is that the property name is “onClick” and you specified “onclick”. It’s actually in camel case and not all lowercase
ah... thanks.

you should change your readme `<datatable :data="data" :columns="columns" :onClick="click"></datatable>` (with camel case)

**Comment by cheezytony** [comment]
@arkgnan thanks for letting me know

**Comment by cheezytony** [comment]
@arkgnan thanks again... I just updated it
